from ._base import BaseTrainingPipeline
from ._train_with_bbox import BBoxExclusiveTrainingPipeline
from ._train_with_segment import SegmentExclusiveTrainingPipeline
from ._train import TrainingPipeline